# Python CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7

    working_directory: ~/openedx-caliper-tracking

    steps:
      - checkout
      - run:
          name: run tests
          command: |
            # Coverage is not shown when we run test script from
            # current directory level so move one step backward.
            cd ..
            ./openedx-caliper-tracking/openedx_caliper_tracking/tests/local_test_script.sh
